/* ============================================================
   DNA 360 — Seeded Exercise Library (~120 movements)
   Includes full Reformer Pilates repertoire, strength, functional,
   and cardiovascular movements.
   ============================================================ */

import type { Exercise } from '@/types/training'

export const SEEDED_EXERCISES: Exercise[] = [
  // ─── REFORMER PILATES (~20 movements) ───
  {
    id: 'ex_ref_footwork_parallel',
    name: 'Reformer Footwork: Parallel Toes & Arches',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['CALVES', 'GLUTES', 'CORE'],
    equipment: 'REFORMER',
    instructions: 'Lie supine with headrest up. Feet on the football, parallel, toes/metatarsals pressed. Press carriage out with controlled triple extension, return with steady spring resistance.',
    isCustom: false,
  },
  {
    id: 'ex_ref_footwork_v_heels',
    name: 'Reformer Footwork: Pilates V & High Half-Toe',
    primaryMuscle: 'CALVES',
    secondaryMuscles: ['QUADS', 'GLUTES'],
    equipment: 'REFORMER',
    instructions: 'Heels glued together in small V position, balls of feet on bar. Drive carriage away smoothly without letting heels drop below bar plane.',
    isCustom: false,
  },
  {
    id: 'ex_ref_hundred',
    name: 'The Hundred on Reformer',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['SHOULDERS', 'CHEST'],
    equipment: 'REFORMER',
    instructions: 'Legs tabletop or 45-degree angle. Straps in hands, curl head, neck, and shoulders off carriage. Pump straight arms vigorously while inhaling 5 counts and exhaling 5 counts.',
    isCustom: false,
  },
  {
    id: 'ex_ref_elephant',
    name: 'Reformer Elephant: Flat Back & Round Back',
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['CALVES', 'CORE', 'SHOULDERS'],
    equipment: 'REFORMER',
    instructions: 'Stand on carriage with heels against shoulder rests, hands on footbar. Press carriage out using hip flexion/extension and pull back using lower abdominals and hamstrings.',
    isCustom: false,
  },
  {
    id: 'ex_ref_long_stretch',
    name: 'Reformer Long Stretch (High Plank Push)',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['SHOULDERS', 'CHEST', 'GLUTES'],
    equipment: 'REFORMER',
    instructions: 'Strong high plank with balls of feet against headrest and hands on footbar. Push carriage back from the shoulders while maintaining neutral pelvis and rock-solid core plank.',
    isCustom: false,
  },
  {
    id: 'ex_ref_knee_stretches',
    name: 'Reformer Knee Stretches (Round & Flat)',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['QUADS', 'GLUTES'],
    equipment: 'REFORMER',
    instructions: 'Kneel facing footbar, feet braced against shoulder rests. Keep upper body stationary and rapidly pump carriage forward and back solely by flexing and extending knees and hips.',
    isCustom: false,
  },
  {
    id: 'ex_ref_short_box_round',
    name: 'Short Box Series: Round Back & Flat Back',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['BACK', 'GLUTES'],
    equipment: 'REFORMER',
    instructions: 'Sit atop short box with feet hooked under safety strap. Hinge or roll pelvis back while maintaining lumbar articulation or tall neutral spine.',
    isCustom: false,
  },
  {
    id: 'ex_ref_short_box_side',
    name: 'Short Box Series: Side-to-Side & Twist',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['BACK', 'SHOULDERS'],
    equipment: 'REFORMER',
    instructions: 'Hold pole overhead, elongate spine, and laterally bend torso over the side of the box, engaging lateral obliques and quadratus lumborum.',
    isCustom: false,
  },
  {
    id: 'ex_ref_mermaid',
    name: 'Reformer Mermaid with Lateral Flexion',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['BACK', 'SHOULDERS'],
    equipment: 'REFORMER',
    instructions: 'Sit sideways in Z-sit position. One hand on footbar, press carriage away while extending opposite arm in a high sweeping arc overhead for deep lateral chain opening.',
    isCustom: false,
  },
  {
    id: 'ex_ref_pulling_straps',
    name: 'Pulling Straps I & II (Prone Lat Sweep)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['SHOULDERS', 'TRICEPS', 'GLUTES'],
    equipment: 'REFORMER',
    instructions: 'Lie prone on long box facing risers, gripping straps. Pull straps straight back past hips into spinal extension, feeling scapular retraction and lat activation.',
    isCustom: false,
  },
  {
    id: 'ex_ref_chest_expansion',
    name: 'Reformer Chest Expansion (Kneeling)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS', 'CORE'],
    equipment: 'REFORMER',
    instructions: 'Kneel tall on carriage facing footbar. Draw strap handles back past hips, pause, rotate head right, then left, look center, and release under control.',
    isCustom: false,
  },
  {
    id: 'ex_ref_jumpboard_plyo',
    name: 'Jumpboard Plyometric Intervals',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['CALVES', 'GLUTES', 'CARDIO'],
    equipment: 'REFORMER',
    instructions: 'Attach jumpboard. Lie supine, perform rhythmic explosive plyometric jumps, focusing on soft toe-ball-heel landing mechanics and core stability.',
    isCustom: false,
  },
  {
    id: 'ex_ref_stomach_massage',
    name: 'Stomach Massage Series: Round & Flat',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['QUADS', 'CALVES'],
    equipment: 'REFORMER',
    instructions: 'Sit on carriage near front edge with pads gripping footbar. Push carriage out, lower and lift heels, then bend knees to return.',
    isCustom: false,
  },
  {
    id: 'ex_ref_feet_in_straps_circles',
    name: 'Feet in Straps: Leg Circles & Frogs',
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['GLUTES', 'CORE'],
    equipment: 'REFORMER',
    instructions: 'Long straps around foot arches. Lower legs to 45 degrees, sweep outwards in expansive circles, and return smoothly to center.',
    isCustom: false,
  },
  {
    id: 'ex_ref_swimming',
    name: 'Reformer Prone Swimming',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'SHOULDERS'],
    equipment: 'REFORMER',
    instructions: 'Lie prone on box holding small straps. Flutter alternate arms and legs while stabilizing pelvis against spring vibration.',
    isCustom: false,
  },
  {
    id: 'ex_ref_eve_lunge',
    name: "Reformer Eve's Lunge (Hip Flexor Release)",
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['QUADS', 'HAMSTRINGS'],
    equipment: 'REFORMER',
    instructions: 'One foot on floor next to carriage, opposite foot against shoulder rest. Drive carriage away into deep controlled hip flexor and quad stretch.',
    isCustom: false,
  },
  {
    id: 'ex_ref_teaser',
    name: 'Reformer Long Box Teaser',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['QUADS', 'SHOULDERS'],
    equipment: 'REFORMER',
    instructions: 'Lie supine on long box with straps in hand. Roll up through spine to V-sit while maintaining 45-degree leg elevation.',
    isCustom: false,
  },
  {
    id: 'ex_ref_side_splits',
    name: 'Reformer Standing Side Splits (Adductor Control)',
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['QUADS', 'CORE'],
    equipment: 'REFORMER',
    instructions: 'One foot on solid platform, one foot on carriage. Stand upright and press carriage away sideways using adductors/abductors under spring load.',
    isCustom: false,
  },

  // ─── CHEST (12 movements) ───
  {
    id: 'ex_bb_bench_press',
    name: 'Barbell Flat Bench Press',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'BARBELL',
    instructions: 'Lie flat on bench, retract scapulae, lower bar under control to mid-sternum, drive bar up vertically locking out elbows smoothly.',
    isCustom: false,
  },
  {
    id: 'ex_bb_incline_bench',
    name: 'Barbell Incline Bench Press',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS', 'TRICEPS'],
    equipment: 'BARBELL',
    instructions: 'Bench at 30-degree incline. Lower bar with elbows tucked at 45 degrees to upper clavicle, press back to lockout.',
    isCustom: false,
  },
  {
    id: 'ex_db_flat_bench',
    name: 'Dumbbell Flat Bench Press',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'DUMBBELL',
    instructions: 'Press dumbbells from shoulder height with neutral or pronated grip, full stretch at bottom, squeeze chest at top.',
    isCustom: false,
  },
  {
    id: 'ex_db_incline_press',
    name: 'Dumbbell Incline Bench Press',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS', 'TRICEPS'],
    equipment: 'DUMBBELL',
    instructions: 'Set bench to 30-45 degrees. Lower dumbbells until level with chest, press up in a slight inward converging arc.',
    isCustom: false,
  },
  {
    id: 'ex_db_chest_flyes',
    name: 'Dumbbell Flat Flyes',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS'],
    equipment: 'DUMBBELL',
    instructions: 'Slight bend at elbows, open arms wide until chest stretches deeply, pull dumbbells back together like hugging a tree.',
    isCustom: false,
  },
  {
    id: 'ex_cable_crossover',
    name: 'Cable High-to-Low Crossover',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS'],
    equipment: 'CABLE',
    instructions: 'Pulleys set high. Step forward in split stance, bring handles down and across lower abdominal line with intense chest contraction.',
    isCustom: false,
  },
  {
    id: 'ex_cable_middle_flye',
    name: 'Cable Mid-Chest Flye',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS'],
    equipment: 'CABLE',
    instructions: 'Pulleys set at chest height. Bring handles together directly in front of sternum, hold peak squeeze for 1 second.',
    isCustom: false,
  },
  {
    id: 'ex_mach_chest_press',
    name: 'Plate-Loaded Seated Chest Press',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'MACHINE',
    instructions: 'Adjust seat so handles align with mid-chest. Plant feet firmly, drive handles forward without protracting shoulders.',
    isCustom: false,
  },
  {
    id: 'ex_mach_pec_deck',
    name: 'Pec Deck Machine Flye',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['SHOULDERS'],
    equipment: 'MACHINE',
    instructions: 'Forearms pressed against pads or handles gripped. Squeeze pads together until touching, slow 3-second negative eccentric.',
    isCustom: false,
  },
  {
    id: 'ex_bw_pushups',
    name: 'Push-Ups (Standard & Deficit)',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'CORE', 'SHOULDERS'],
    equipment: 'BODYWEIGHT',
    instructions: 'Hands shoulder-width apart, core braced. Lower chest until 1 inch off floor or deficit blocks, push back up explosively.',
    isCustom: false,
  },
  {
    id: 'ex_bw_dips_chest',
    name: 'Chest Dips (Forward Lean)',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'BODYWEIGHT',
    instructions: 'Grip parallel bars, tilt torso forward 30 degrees, flare elbows slightly, dip until shoulders pass elbows, drive up.',
    isCustom: false,
  },
  {
    id: 'ex_db_decline_press',
    name: 'Dumbbell Decline Bench Press',
    primaryMuscle: 'CHEST',
    secondaryMuscles: ['TRICEPS', 'SHOULDERS'],
    equipment: 'DUMBBELL',
    instructions: 'Set bench to 15-20 degree decline, secure shins under rollers, press dumbbells vertically over lower pec line.',
    isCustom: false,
  },

  // ─── BACK (14 movements) ───
  {
    id: 'ex_bb_deadlift_conv',
    name: 'Conventional Barbell Deadlift',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'CORE', 'TRICEPS'],
    equipment: 'BARBELL',
    instructions: 'Feet hip-width, grip bar outside shins, pull slack out of bar, drive floor away with quads and glutes, lockout hips tall.',
    isCustom: false,
  },
  {
    id: 'ex_bb_bent_row',
    name: 'Barbell Bent-Over Row (Pendlay & Conventional)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'CORE', 'SHOULDERS'],
    equipment: 'BARBELL',
    instructions: 'Hinge hips to 45 or 90 degrees, pull bar towards belly button while pulling shoulder blades back together, lower under control.',
    isCustom: false,
  },
  {
    id: 'ex_bw_pullups',
    name: 'Pull-Ups (Pronated Grip)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'CORE'],
    equipment: 'BODYWEIGHT',
    instructions: 'Grip bar slightly wider than shoulders, depress scapulae, pull chest to bar, lower smoothly to full dead-hang extension.',
    isCustom: false,
  },
  {
    id: 'ex_bw_chinups',
    name: 'Chin-Ups (Supinated Grip)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'CORE'],
    equipment: 'BODYWEIGHT',
    instructions: 'Palms facing you, pull chin over bar, intense engagement of lats and biceps, full range of motion.',
    isCustom: false,
  },
  {
    id: 'ex_lat_pulldown_wide',
    name: 'Lat Pulldown (Wide Grip)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'SHOULDERS'],
    equipment: 'CABLE',
    instructions: 'Sit with thighs locked under pads. Pull bar to upper chest with proud ribcage, avoid excessive backward swinging.',
    isCustom: false,
  },
  {
    id: 'ex_lat_pulldown_close',
    name: 'Close-Grip V-Bar Pulldown',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'SHOULDERS'],
    equipment: 'CABLE',
    instructions: 'Attach neutral V-handle, pull towards sternum, retracting lats and thoracic spine into extension.',
    isCustom: false,
  },
  {
    id: 'ex_cable_seated_row',
    name: 'Seated Cable Row (Neutral Grip)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'SHOULDERS'],
    equipment: 'CABLE',
    instructions: 'Sit tall with slight knee bend. Pull handle to navel while pulling shoulders down and back, stretch arms forward without rounding lower back.',
    isCustom: false,
  },
  {
    id: 'ex_db_one_arm_row',
    name: 'Dumbbell Single-Arm Row',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'CORE'],
    equipment: 'DUMBBELL',
    instructions: 'Brace one hand on bench, flat back. Pull dumbbell towards hip pocket, keeping elbow tucked close to ribcage.',
    isCustom: false,
  },
  {
    id: 'ex_tbar_row',
    name: 'T-Bar Row (Chest Supported)',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS', 'SHOULDERS'],
    equipment: 'MACHINE',
    instructions: 'Chest against pad, pull handles back, maximizing upper back thickness and rhomboid recruitment.',
    isCustom: false,
  },
  {
    id: 'ex_cable_straight_arm_pulldown',
    name: 'Cable Straight-Arm Lat Pulldown',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['TRICEPS', 'CORE'],
    equipment: 'CABLE',
    instructions: 'Slight forward lean, arms straight with soft elbow bend. Sweep bar down in an arc to thighs, feeling lats isolate.',
    isCustom: false,
  },
  {
    id: 'ex_face_pull_cable',
    name: 'Cable Rope Face Pulls',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['SHOULDERS', 'TRICEPS'],
    equipment: 'CABLE',
    instructions: 'Pulleys at eye level. Pull rope ends toward ears, externally rotating shoulders, great for rotator cuff health.',
    isCustom: false,
  },
  {
    id: 'ex_hyperextension_back',
    name: '45-Degree Back Hyperextension',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS'],
    equipment: 'BODYWEIGHT',
    instructions: 'Support hips on pad. Hinge from waist, lower torso, raise body up to straight line using lower back erectors and glutes.',
    isCustom: false,
  },
  {
    id: 'ex_mach_lat_row_iso',
    name: 'ISO-Lateral Plate Loaded High Row',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['BICEPS'],
    equipment: 'MACHINE',
    instructions: 'Single arm or bilateral pull from high angle down to hips, targeting lower lat fibers.',
    isCustom: false,
  },
  {
    id: 'ex_bb_shrugs',
    name: 'Barbell Trap Shrugs',
    primaryMuscle: 'BACK',
    secondaryMuscles: ['SHOULDERS'],
    equipment: 'BARBELL',
    instructions: 'Hold bar in front with overhand grip. Shrug shoulders straight up toward ears, pause at peak, lower slowly.',
    isCustom: false,
  },

  // ─── SHOULDERS (10 movements) ───
  {
    id: 'ex_bb_overhead_press',
    name: 'Barbell Standing Overhead Press (OHP)',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['TRICEPS', 'CORE'],
    equipment: 'BARBELL',
    instructions: 'Stand tall, squeeze glutes and abs. Press bar overhead in straight path, bringing head forward through the window at top.',
    isCustom: false,
  },
  {
    id: 'ex_db_seated_shoulder_press',
    name: 'Dumbbell Seated Shoulder Press',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['TRICEPS'],
    equipment: 'DUMBBELL',
    instructions: 'Sit on high-backed bench. Press dumbbells overhead from ear level, touching lightly at top before controlled lowering.',
    isCustom: false,
  },
  {
    id: 'ex_db_lateral_raise',
    name: 'Dumbbell Standing Lateral Raise',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['BACK'],
    equipment: 'DUMBBELL',
    instructions: 'Slight forward lean, raise arms to sides until parallel with floor, lead with elbows, avoid swinging torso.',
    isCustom: false,
  },
  {
    id: 'ex_cable_lateral_raise',
    name: 'Single-Arm Cable Lateral Raise',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['BACK'],
    equipment: 'CABLE',
    instructions: 'Low pulley, reach across body or behind back, raise handle up and outward maintaining continuous spring tension.',
    isCustom: false,
  },
  {
    id: 'ex_db_arnold_press',
    name: 'Arnold Dumbbell Press',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['TRICEPS'],
    equipment: 'DUMBBELL',
    instructions: 'Start with palms facing chest, rotate wrists outward as you press overhead, finish with palms facing away.',
    isCustom: false,
  },
  {
    id: 'ex_db_rear_delt_flye',
    name: 'Dumbbell Bent-Over Rear Delt Flye',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['BACK'],
    equipment: 'DUMBBELL',
    instructions: 'Hinge over at hips, raise dumbbells outward with elbows slightly bent, squeezing posterior delts.',
    isCustom: false,
  },
  {
    id: 'ex_mach_reverse_pec_deck',
    name: 'Machine Reverse Pec Deck (Rear Delts)',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['BACK'],
    equipment: 'MACHINE',
    instructions: 'Sit facing machine, arms straight gripping handles, push arms backward in horizontal abduction.',
    isCustom: false,
  },
  {
    id: 'ex_bb_upright_row',
    name: 'Barbell Upright Row',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['BACK', 'BICEPS'],
    equipment: 'BARBELL',
    instructions: 'Grip bar shoulder-width, pull straight up along torso leading with elbows up to chest height.',
    isCustom: false,
  },
  {
    id: 'ex_db_front_raise',
    name: 'Dumbbell Alternate Front Raise',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['CORE'],
    equipment: 'DUMBBELL',
    instructions: 'Raise dumbbells forward one at a time to eye level with neutral or pronated grip.',
    isCustom: false,
  },
  {
    id: 'ex_mach_shoulder_press',
    name: 'Plate-Loaded Machine Shoulder Press',
    primaryMuscle: 'SHOULDERS',
    secondaryMuscles: ['TRICEPS'],
    equipment: 'MACHINE',
    instructions: 'Adjust seat so handles are at shoulder level, press upward with smooth arc.',
    isCustom: false,
  },

  // ─── LEGS: QUADS, HAMSTRINGS, GLUTES, CALVES (18 movements) ───
  {
    id: 'ex_bb_back_squat',
    name: 'Barbell Back Squat (High Bar / Low Bar)',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'CORE'],
    equipment: 'BARBELL',
    instructions: 'Bar resting on traps, feet shoulder-width. Descend hips back and down until hip crease is below knee, drive up through midfoot.',
    isCustom: false,
  },
  {
    id: 'ex_bb_front_squat',
    name: 'Barbell Front Squat',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['CORE', 'GLUTES'],
    equipment: 'BARBELL',
    instructions: 'Clean rack or crossed-arm hold on clavicle, elbows high. Squat deep while maintaining completely vertical torso.',
    isCustom: false,
  },
  {
    id: 'ex_mach_leg_press',
    name: '45-Degree Incline Leg Press',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS'],
    equipment: 'MACHINE',
    instructions: 'Feet placed mid-platform. Release safety, lower sled until knees reach 90 degrees without rounding lower back, press up without locking knees.',
    isCustom: false,
  },
  {
    id: 'ex_mach_hack_squat',
    name: 'Hack Squat Machine',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES'],
    equipment: 'MACHINE',
    instructions: 'Back flat against sled, shoulders locked under pads. Squat down to parallel and press sled up smoothly.',
    isCustom: false,
  },
  {
    id: 'ex_mach_leg_extension',
    name: 'Leg Extension Machine',
    primaryMuscle: 'QUADS',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    instructions: 'Back against pad, shin pad just above ankles. Extend knees fully, hold peak contraction for 1 second, lower slowly.',
    isCustom: false,
  },
  {
    id: 'ex_bb_romanian_deadlift',
    name: 'Barbell Romanian Deadlift (RDL)',
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['GLUTES', 'BACK'],
    equipment: 'BARBELL',
    instructions: 'Slight knee bend fixed in place. Push hips backward while lowering bar down shins until deep hamstring stretch, thrust hips forward to return.',
    isCustom: false,
  },
  {
    id: 'ex_db_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['GLUTES', 'BACK'],
    equipment: 'DUMBBELL',
    instructions: 'Hold pair of dumbbells close to thighs, hinge at hips keeping spine neutral, contract glutes and hamstrings to stand.',
    isCustom: false,
  },
  {
    id: 'ex_mach_lying_leg_curl',
    name: 'Lying Hamstring Leg Curl',
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: ['CALVES'],
    equipment: 'MACHINE',
    instructions: 'Lie prone with roller pad against lower calves. Curl heels towards glutes without lifting hips off bench.',
    isCustom: false,
  },
  {
    id: 'ex_mach_seated_leg_curl',
    name: 'Seated Hamstring Leg Curl',
    primaryMuscle: 'HAMSTRINGS',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    instructions: 'Lock lap pad down tightly. Curl heels underneath seat smoothly, slow controlled release.',
    isCustom: false,
  },
  {
    id: 'ex_bb_hip_thrust',
    name: 'Barbell Glute Hip Thrust',
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: 'BARBELL',
    instructions: 'Upper back braced on bench, padded barbell over hips. Drive through heels to full hip extension, forming a tabletop with torso and thighs.',
    isCustom: false,
  },
  {
    id: 'ex_db_walking_lunges',
    name: 'Dumbbell Walking Lunges',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'CALVES'],
    equipment: 'DUMBBELL',
    instructions: 'Hold dumbbells at sides. Step forward into lunge with back knee lightly kissing floor, drive forward onto next stride.',
    isCustom: false,
  },
  {
    id: 'ex_db_bulgarian_split_squat',
    name: 'Bulgarian Split Squat (Rear Foot Elevated)',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES', 'HAMSTRINGS'],
    equipment: 'DUMBBELL',
    instructions: 'One foot elevated behind on bench. Descend on front leg until thigh is parallel to ground, drive through front heel.',
    isCustom: false,
  },
  {
    id: 'ex_mach_glute_kickback',
    name: 'Cable / Machine Glute Kickback',
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['HAMSTRINGS'],
    equipment: 'CABLE',
    instructions: 'Ankle strap attached to low cable. Kick leg back and up, squeezing glute at top without arching lower back.',
    isCustom: false,
  },
  {
    id: 'ex_mach_standing_calf_raise',
    name: 'Standing Machine Calf Raise',
    primaryMuscle: 'CALVES',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    instructions: 'Balls of feet on block, shoulders under pads. Drop heels for full stretch, drive up onto toes as high as possible.',
    isCustom: false,
  },
  {
    id: 'ex_mach_seated_calf_raise',
    name: 'Seated Calf Raise (Soleus)',
    primaryMuscle: 'CALVES',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    instructions: 'Sit with knees under pads. Full ankle plantar flexion and dorsiflexion, 2-second pause at bottom stretch.',
    isCustom: false,
  },
  {
    id: 'ex_bw_sissy_squats',
    name: 'Bodyweight Sissy Squat',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['CORE'],
    equipment: 'BODYWEIGHT',
    instructions: 'Lean torso back while pushing knees forward on toes, deep quad stretch, return using knee extension.',
    isCustom: false,
  },
  {
    id: 'ex_mach_hip_abduction',
    name: 'Seated Hip Abduction Machine',
    primaryMuscle: 'GLUTES',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    instructions: 'Sit tall against backrest, press pads outward opening legs wide, hold peak gluteus medius contraction.',
    isCustom: false,
  },
  {
    id: 'ex_mach_hip_adduction',
    name: 'Seated Hip Adduction Machine',
    primaryMuscle: 'GLUTES',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    instructions: 'Sit with legs wide outside pads, squeeze pads together until touching at midline.',
    isCustom: false,
  },

  // ─── ARMS: BICEPS & TRICEPS (14 movements) ───
  {
    id: 'ex_bb_bicep_curl',
    name: 'Barbell Standing Bicep Curl',
    primaryMuscle: 'BICEPS',
    secondaryMuscles: ['CORE'],
    equipment: 'BARBELL',
    instructions: 'Shoulder-width underhand grip. Curl bar upward towards chest keeping elbows pinned to ribs, lower with control.',
    isCustom: false,
  },
  {
    id: 'ex_bb_ez_bar_preacher_curl',
    name: 'EZ-Bar Preacher Curl',
    primaryMuscle: 'BICEPS',
    secondaryMuscles: [],
    equipment: 'BARBELL',
    instructions: 'Triceps flat against preacher bench slant. Curl bar to vertical without lifting elbows off pad.',
    isCustom: false,
  },
  {
    id: 'ex_db_incline_bicep_curl',
    name: 'Dumbbell Incline Bicep Curl',
    primaryMuscle: 'BICEPS',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    instructions: 'Sit back on 45-60 degree bench with arms hanging down. Curl dumbbells while keeping shoulders retracted for maximum long head stretch.',
    isCustom: false,
  },
  {
    id: 'ex_db_hammer_curl',
    name: 'Dumbbell Neutral Hammer Curl',
    primaryMuscle: 'BICEPS',
    secondaryMuscles: ['BACK'],
    equipment: 'DUMBBELL',
    instructions: 'Palms facing each other throughout movement, curls target brachialis and brachioradialis for arm thickness.',
    isCustom: false,
  },
  {
    id: 'ex_cable_bicep_curl',
    name: 'Cable Straight-Bar Curl',
    primaryMuscle: 'BICEPS',
    secondaryMuscles: [],
    equipment: 'CABLE',
    instructions: 'Low pulley, continuous tension on bicep throughout the full arc of the curl.',
    isCustom: false,
  },
  {
    id: 'ex_db_concentration_curl',
    name: 'Seated Concentration Curl',
    primaryMuscle: 'BICEPS',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    instructions: 'Elbow braced against inner thigh, curl dumbbell towards chin with strict isolation.',
    isCustom: false,
  },
  {
    id: 'ex_cable_tricep_pushdown_rope',
    name: 'Cable Tricep Rope Pushdown',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'CABLE',
    instructions: 'High pulley, elbows locked at sides. Push rope down and spread ends apart at bottom for peak tricep lockout.',
    isCustom: false,
  },
  {
    id: 'ex_cable_tricep_pushdown_bar',
    name: 'Cable Straight-Bar Pushdown',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'CABLE',
    instructions: 'Overhand grip on small straight bar, press down to thighs locking out triceps smoothly.',
    isCustom: false,
  },
  {
    id: 'ex_bb_skullcrushers',
    name: 'Barbell / EZ-Bar Skullcrushers (Lying Extension)',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'BARBELL',
    instructions: 'Lie on flat bench, press bar overhead. Hinge elbows lowering bar towards forehead/crown, extend back to lockout.',
    isCustom: false,
  },
  {
    id: 'ex_cable_overhead_tricep_ext',
    name: 'Cable Overhead Rope Extension',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'CABLE',
    instructions: 'Facing away from high pulley, lean forward and extend rope overhead until arms are straight.',
    isCustom: false,
  },
  {
    id: 'ex_db_overhead_tricep_ext',
    name: 'Dumbbell Seated Overhead Extension',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    instructions: 'Hold single heavy dumbbell with both hands cupped under top plates, lower behind neck, press to lockout.',
    isCustom: false,
  },
  {
    id: 'ex_bb_close_grip_bench',
    name: 'Close-Grip Barbell Bench Press',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: ['CHEST', 'SHOULDERS'],
    equipment: 'BARBELL',
    instructions: 'Hands shoulder-width apart, elbows tucked close to sides, press bar focusing on tricep recruitment.',
    isCustom: false,
  },
  {
    id: 'ex_bw_parallel_bar_dips',
    name: 'Parallel Bar Dips (Tricep Focus)',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: ['CHEST', 'SHOULDERS'],
    equipment: 'BODYWEIGHT',
    instructions: 'Keep body upright with legs straight, bend elbows to 90 degrees and push back up locking out triceps.',
    isCustom: false,
  },
  {
    id: 'ex_db_kickbacks',
    name: 'Dumbbell Tricep Kickback',
    primaryMuscle: 'TRICEPS',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    instructions: 'Torso hinged horizontal, upper arm parallel to floor, extend forearm back until arm is locked straight.',
    isCustom: false,
  },

  // ─── CORE & FUNCTIONAL (12 movements) ───
  {
    id: 'ex_core_plank',
    name: 'Forearm Front Plank Hold',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['SHOULDERS', 'GLUTES'],
    equipment: 'BODYWEIGHT',
    instructions: 'Rest on forearms and toes. Squeeze glutes, quads, and pull belly button to spine, maintaining a perfectly straight line.',
    isCustom: false,
  },
  {
    id: 'ex_core_hanging_leg_raise',
    name: 'Hanging Leg / Knee Raise',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['BACK'],
    equipment: 'BODYWEIGHT',
    instructions: 'Hang from pull-up bar, raise toes or knees to chest height by tucking pelvis upward without swinging.',
    isCustom: false,
  },
  {
    id: 'ex_cable_woodchopper',
    name: 'Cable Diagonal Woodchopper',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['SHOULDERS', 'BACK'],
    equipment: 'CABLE',
    instructions: 'Set cable high. Rotate torso diagonally downward across opposite knee using obliques, return smoothly.',
    isCustom: false,
  },
  {
    id: 'ex_core_ab_wheel_rollout',
    name: 'Abdominal Wheel Rollout',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['BACK', 'SHOULDERS'],
    equipment: 'OTHER',
    instructions: 'Kneel holding wheel handles. Roll wheel forward extending body as low as possible while keeping core braced, pull back with abs.',
    isCustom: false,
  },
  {
    id: 'ex_cable_kneeling_crunch',
    name: 'Kneeling Cable Rope Crunch',
    primaryMuscle: 'CORE',
    secondaryMuscles: [],
    equipment: 'CABLE',
    instructions: 'Kneel facing cable stack holding rope ends at ears. Curl elbows down toward knees curling spine into flexion.',
    isCustom: false,
  },
  {
    id: 'ex_core_russian_twist',
    name: 'Russian Twists with Plate / Medicine Ball',
    primaryMuscle: 'CORE',
    secondaryMuscles: [],
    equipment: 'OTHER',
    instructions: 'Sit in V-up position with heels elevated. Rotate weight from hip to hip under controlled tempo.',
    isCustom: false,
  },
  {
    id: 'ex_core_deadbug',
    name: 'Deadbug Isometric Contralateral Reach',
    primaryMuscle: 'CORE',
    secondaryMuscles: [],
    equipment: 'BODYWEIGHT',
    instructions: 'Lie on back, lower back pressed flat into floor. Extend opposite arm and leg while stabilizing lumbo-pelvic core.',
    isCustom: false,
  },
  {
    id: 'ex_core_side_plank',
    name: 'Side Plank with Hip Dip',
    primaryMuscle: 'CORE',
    secondaryMuscles: ['GLUTES'],
    equipment: 'BODYWEIGHT',
    instructions: 'Support body on one forearm and edges of feet, dip hip toward floor and elevate back up to high straight alignment.',
    isCustom: false,
  },
  {
    id: 'ex_kb_kettlebell_swing',
    name: 'Kettlebell Russian / American Swing',
    primaryMuscle: 'GLUTES',
    secondaryMuscles: ['HAMSTRINGS', 'BACK', 'CORE', 'CARDIO'],
    equipment: 'KETTLEBELL',
    instructions: 'Hike kettlebell between legs with hip hinge, snap hips forward explosively driving bell to chest level.',
    isCustom: false,
  },
  {
    id: 'ex_kb_turkish_getup',
    name: 'Turkish Get-Up',
    primaryMuscle: 'FULL_BODY',
    secondaryMuscles: ['SHOULDERS', 'CORE', 'GLUTES'],
    equipment: 'KETTLEBELL',
    instructions: 'Sequential ground-to-standing movement with kettlebell locked out overhead throughout.',
    isCustom: false,
  },
  {
    id: 'ex_kb_goblet_squat',
    name: 'Kettlebell / Dumbbell Goblet Squat',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES', 'CORE'],
    equipment: 'KETTLEBELL',
    instructions: 'Hold weight tight against chest, squat deep tracking knees over toes, pause at bottom.',
    isCustom: false,
  },
  {
    id: 'ex_farmers_walk',
    name: "Heavy Farmer's Carry",
    primaryMuscle: 'FULL_BODY',
    secondaryMuscles: ['BACK', 'CORE', 'CALVES'],
    equipment: 'DUMBBELL',
    instructions: 'Hold two heavy dumbbells or kettlebells at sides, walk tall with short brisk strides and shoulders back.',
    isCustom: false,
  },

  // ─── CARDIO & CONDITIONING (10 movements) ───
  {
    id: 'ex_cardio_treadmill_run',
    name: 'Treadmill Incline Run / Walk',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['CALVES', 'QUADS', 'GLUTES'],
    equipment: 'CARDIO_MACHINE',
    instructions: 'Set speed and incline, maintain steady aerobic or interval running mechanics.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_concept2_rower',
    name: 'Concept2 Indoor Rower',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['BACK', 'LEGS', 'CORE', 'BICEPS'] as any,
    equipment: 'CARDIO_MACHINE',
    instructions: 'Drive with legs, lean body back, pull handle to lower ribs. Reverse smoothly.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_skierg',
    name: 'Concept2 SkiErg',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['BACK', 'TRICEPS', 'CORE'],
    equipment: 'CARDIO_MACHINE',
    instructions: 'Stand tall facing SkiErg, pull handles down in rhythmic double-pole motion with soft knee bend.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_assault_bike',
    name: 'Air Bike / Assault Bike Sprints',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['QUADS', 'SHOULDERS', 'FULL_BODY'],
    equipment: 'CARDIO_MACHINE',
    instructions: 'Push and pull handles while pedaling with maximum RPM effort for interval bursts.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_rpm_spin',
    name: 'RPM Magnetic Spinning Bike',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['QUADS', 'HAMSTRINGS', 'CALVES'],
    equipment: 'CARDIO_MACHINE',
    instructions: 'Cadence work and resistance hill climbs.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_stairmaster',
    name: 'StairMaster Revolving Climber',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['GLUTES', 'QUADS', 'CALVES'],
    equipment: 'CARDIO_MACHINE',
    instructions: 'Continuous stair climbing without resting bodyweight onto handrails.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_jump_rope',
    name: 'Speed Jump Rope Intervals',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['CALVES', 'SHOULDERS'],
    equipment: 'OTHER',
    instructions: 'Rhythmic bounding on balls of feet, double unders or high-cadence singles.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_battle_ropes',
    name: 'Heavy Battle Rope Waves & Slams',
    primaryMuscle: 'CARDIO',
    secondaryMuscles: ['SHOULDERS', 'CORE', 'BACK'],
    equipment: 'OTHER',
    instructions: 'Alternate waves, bilateral slams, lateral whip waves in athletic half-squat stance.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_sled_push',
    name: 'Prowler Turf Sled Push & Drag',
    primaryMuscle: 'QUADS',
    secondaryMuscles: ['GLUTES', 'CALVES', 'CARDIO'],
    equipment: 'OTHER',
    instructions: 'Arms locked on upright poles, drive turf sled with powerful deep leg drives.',
    isCustom: false,
  },
  {
    id: 'ex_cardio_burpees',
    name: 'Chest-to-Floor Burpees',
    primaryMuscle: 'FULL_BODY',
    secondaryMuscles: ['CARDIO', 'CHEST', 'QUADS'],
    equipment: 'BODYWEIGHT',
    instructions: 'Drop chest to floor, snap feet forward under hips, jump upward with hands overhead.',
    isCustom: false,
  },
]
