/* ============================================================
   DNA 360 — Seeded Gym Library Programs
   Curated by Head Coach Rajesh Poojary & Hemant Shirke (Reformer Lead)
   Available to all 679 members for 2-tap clone & start.
   ============================================================ */

import type { Program } from '@/types/training'

export const SEEDED_GYM_PROGRAMS: Program[] = [
  // 1. Beginner Full Body (3 Days/Week)
  {
    id: 'prog_lib_beginner_fb',
    name: 'Beginner Full Body Foundation',
    goal: 'GENERAL',
    weeks: 4,
    daysPerWeek: 3,
    notes: 'Ideal introductory 3-day split focusing on compound movement mechanics, motor control, and foundational hypertrophy. Rest 1 day between sessions.',
    ownerType: 'GYM',
    ownerId: 'gym_powai',
    visibility: 'GYM_LIBRARY',
    clonedFromId: null,
    days: [
      {
        id: 'day_fb_1',
        programId: 'prog_lib_beginner_fb',
        weekIndex: 0,
        dayIndex: 0,
        label: 'Day 1: Full Body A (Squat & Press Focus)',
        exercises: [
          {
            id: 'pe_fb1_1',
            programDayId: 'day_fb_1',
            exerciseId: 'ex_bb_back_squat',
            order: 1,
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            targetWeight: 50,
            rpe: 7.5,
            restSeconds: 90,
            tempo: '3-0-1-0',
            supersetTag: null,
            coachNote: 'Focus on hitting parallel depth and keeping torso braced.',
            isOptional: false,
          },
          {
            id: 'pe_fb1_2',
            programDayId: 'day_fb_1',
            exerciseId: 'ex_bb_bench_press',
            order: 2,
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            targetWeight: 45,
            rpe: 7.5,
            restSeconds: 90,
            tempo: '2-1-1-0',
            supersetTag: null,
            coachNote: 'Touch mid-sternum, keep shoulder blades pinned into bench.',
            isOptional: false,
          },
          {
            id: 'pe_fb1_3',
            programDayId: 'day_fb_1',
            exerciseId: 'ex_lat_pulldown_wide',
            order: 3,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 40,
            rpe: 7.0,
            restSeconds: 60,
            tempo: '2-0-1-1',
            supersetTag: null,
            coachNote: 'Drive elbows down into hips, squeeze lats.',
            isOptional: false,
          },
          {
            id: 'pe_fb1_4',
            programDayId: 'day_fb_1',
            exerciseId: 'ex_db_romanian_deadlift',
            order: 4,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 16,
            rpe: 7.0,
            restSeconds: 60,
            tempo: '3-1-1-0',
            supersetTag: null,
            coachNote: 'Hinge hips back, slight knee bend, feel hamstring tension.',
            isOptional: false,
          },
          {
            id: 'pe_fb1_5',
            programDayId: 'day_fb_1',
            exerciseId: 'ex_core_plank',
            order: 5,
            sets: 3,
            repsMin: 1,
            repsMax: 1,
            targetWeight: 0,
            rpe: 8.0,
            restSeconds: 45,
            tempo: 'Hold 45s',
            supersetTag: null,
            coachNote: 'Squeeze glutes and abs, don’t let lower back sag.',
            isOptional: true,
          },
        ],
      },
      {
        id: 'day_fb_2',
        programId: 'prog_lib_beginner_fb',
        weekIndex: 0,
        dayIndex: 1,
        label: 'Day 2: Full Body B (Hinge & Pull Focus)',
        exercises: [
          {
            id: 'pe_fb2_1',
            programDayId: 'day_fb_2',
            exerciseId: 'ex_bb_deadlift_conv',
            order: 1,
            sets: 3,
            repsMin: 6,
            repsMax: 8,
            targetWeight: 70,
            rpe: 7.5,
            restSeconds: 120,
            tempo: '2-1-1-0',
            supersetTag: null,
            coachNote: 'Pull the slack out of the bar before pushing the floor away.',
            isOptional: false,
          },
          {
            id: 'pe_fb2_2',
            programDayId: 'day_fb_2',
            exerciseId: 'ex_bb_overhead_press',
            order: 2,
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            targetWeight: 30,
            rpe: 7.5,
            restSeconds: 90,
            tempo: '2-0-1-0',
            supersetTag: null,
            coachNote: 'Press vertically overhead, tuck head forward at lockout.',
            isOptional: false,
          },
          {
            id: 'pe_fb2_3',
            programDayId: 'day_fb_2',
            exerciseId: 'ex_cable_seated_row',
            order: 3,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 45,
            rpe: 7.0,
            restSeconds: 60,
            tempo: '2-0-1-1',
            supersetTag: null,
            coachNote: 'Sit tall, pull handles to navel with scapular retraction.',
            isOptional: false,
          },
          {
            id: 'pe_fb2_4',
            programDayId: 'day_fb_2',
            exerciseId: 'ex_mach_leg_press',
            order: 4,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 100,
            rpe: 7.5,
            restSeconds: 90,
            tempo: '3-0-1-0',
            supersetTag: null,
            coachNote: 'Full depth without tailbone tucking off the backrest.',
            isOptional: false,
          },
        ],
      },
      {
        id: 'day_fb_3',
        programId: 'prog_lib_beginner_fb',
        weekIndex: 0,
        dayIndex: 2,
        label: 'Day 3: Full Body C (Hypertrophy & Core)',
        exercises: [
          {
            id: 'pe_fb3_1',
            programDayId: 'day_fb_3',
            exerciseId: 'ex_db_incline_press',
            order: 1,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 18,
            rpe: 7.5,
            restSeconds: 75,
            tempo: '2-1-1-0',
            supersetTag: null,
            coachNote: '30-degree incline, stretch chest at bottom.',
            isOptional: false,
          },
          {
            id: 'pe_fb3_2',
            programDayId: 'day_fb_3',
            exerciseId: 'ex_db_one_arm_row',
            order: 2,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 18,
            rpe: 7.5,
            restSeconds: 60,
            tempo: '2-0-1-1',
            supersetTag: null,
            coachNote: 'Pull elbow toward hip crease.',
            isOptional: false,
          },
          {
            id: 'pe_fb3_3',
            programDayId: 'day_fb_3',
            exerciseId: 'ex_db_walking_lunges',
            order: 3,
            sets: 3,
            repsMin: 12,
            repsMax: 14,
            targetWeight: 12,
            rpe: 8.0,
            restSeconds: 60,
            tempo: '1-0-1-0',
            supersetTag: null,
            coachNote: 'Smooth controlled strides along turf.',
            isOptional: false,
          },
          {
            id: 'pe_fb3_4',
            programDayId: 'day_fb_3',
            exerciseId: 'ex_cable_tricep_pushdown_rope',
            order: 4,
            sets: 3,
            repsMin: 12,
            repsMax: 15,
            targetWeight: 20,
            rpe: 7.0,
            restSeconds: 45,
            tempo: '2-0-1-1',
            supersetTag: 'SS1',
            coachNote: 'Superset with bicep curls.',
            isOptional: true,
          },
          {
            id: 'pe_fb3_5',
            programDayId: 'day_fb_3',
            exerciseId: 'ex_bb_bicep_curl',
            order: 5,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 20,
            rpe: 7.0,
            restSeconds: 60,
            tempo: '2-0-1-1',
            supersetTag: 'SS1',
            coachNote: 'Superset with tricep pushdowns.',
            isOptional: true,
          },
        ],
      },
    ],
  },

  // 2. Push / Pull / Legs Hypertrophy (6 Days/Week)
  {
    id: 'prog_lib_ppl',
    name: 'Push / Pull / Legs (PPL) Hypertrophy',
    goal: 'MUSCLE_GAIN',
    weeks: 4,
    daysPerWeek: 6,
    notes: 'Classic high-frequency hypertrophy routine split into Push (Chest/Delts/Triceps), Pull (Back/Traps/Biceps), and Legs (Quads/Hams/Calves). Run 6 days on, 1 day off.',
    ownerType: 'GYM',
    ownerId: 'gym_powai',
    visibility: 'GYM_LIBRARY',
    clonedFromId: null,
    days: [
      {
        id: 'day_ppl_push1',
        programId: 'prog_lib_ppl',
        weekIndex: 0,
        dayIndex: 0,
        label: 'Push A: Strength & Upper Pecs',
        exercises: [
          {
            id: 'pe_ppl_p1',
            programDayId: 'day_ppl_push1',
            exerciseId: 'ex_bb_bench_press',
            order: 1,
            sets: 4,
            repsMin: 6,
            repsMax: 8,
            targetWeight: 65,
            rpe: 8.0,
            restSeconds: 120,
            isOptional: false,
          },
          {
            id: 'pe_ppl_p2',
            programDayId: 'day_ppl_push1',
            exerciseId: 'ex_db_incline_press',
            order: 2,
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            targetWeight: 22,
            rpe: 8.0,
            restSeconds: 90,
            isOptional: false,
          },
          {
            id: 'pe_ppl_p3',
            programDayId: 'day_ppl_push1',
            exerciseId: 'ex_db_lateral_raise',
            order: 3,
            sets: 4,
            repsMin: 12,
            repsMax: 15,
            targetWeight: 10,
            rpe: 8.5,
            restSeconds: 60,
            isOptional: false,
          },
          {
            id: 'pe_ppl_p4',
            programDayId: 'day_ppl_push1',
            exerciseId: 'ex_cable_tricep_pushdown_rope',
            order: 4,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 25,
            rpe: 8.0,
            restSeconds: 60,
            isOptional: false,
          },
        ],
      },
      {
        id: 'day_ppl_pull1',
        programId: 'prog_lib_ppl',
        weekIndex: 0,
        dayIndex: 1,
        label: 'Pull A: Lat Width & Thickness',
        exercises: [
          {
            id: 'pe_ppl_pl1',
            programDayId: 'day_ppl_pull1',
            exerciseId: 'ex_bb_bent_row',
            order: 1,
            sets: 4,
            repsMin: 6,
            repsMax: 8,
            targetWeight: 60,
            rpe: 8.0,
            restSeconds: 120,
            isOptional: false,
          },
          {
            id: 'pe_ppl_pl2',
            programDayId: 'day_ppl_pull1',
            exerciseId: 'ex_bw_pullups',
            order: 2,
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            targetWeight: 0,
            rpe: 8.5,
            restSeconds: 90,
            isOptional: false,
          },
          {
            id: 'pe_ppl_pl3',
            programDayId: 'day_ppl_pull1',
            exerciseId: 'ex_face_pull_cable',
            order: 3,
            sets: 3,
            repsMin: 12,
            repsMax: 15,
            targetWeight: 20,
            rpe: 7.5,
            restSeconds: 60,
            isOptional: false,
          },
          {
            id: 'pe_ppl_pl4',
            programDayId: 'day_ppl_pull1',
            exerciseId: 'ex_db_incline_bicep_curl',
            order: 4,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 12,
            rpe: 8.0,
            restSeconds: 60,
            isOptional: false,
          },
        ],
      },
      {
        id: 'day_ppl_leg1',
        programId: 'prog_lib_ppl',
        weekIndex: 0,
        dayIndex: 2,
        label: 'Legs A: Quad Dominant & Calves',
        exercises: [
          {
            id: 'pe_ppl_l1',
            programDayId: 'day_ppl_leg1',
            exerciseId: 'ex_bb_back_squat',
            order: 1,
            sets: 4,
            repsMin: 6,
            repsMax: 8,
            targetWeight: 75,
            rpe: 8.0,
            restSeconds: 120,
            isOptional: false,
          },
          {
            id: 'pe_ppl_l2',
            programDayId: 'day_ppl_leg1',
            exerciseId: 'ex_mach_leg_press',
            order: 2,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 140,
            rpe: 8.0,
            restSeconds: 90,
            isOptional: false,
          },
          {
            id: 'pe_ppl_l3',
            programDayId: 'day_ppl_leg1',
            exerciseId: 'ex_mach_lying_leg_curl',
            order: 3,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            targetWeight: 45,
            rpe: 8.0,
            restSeconds: 60,
            isOptional: false,
          },
          {
            id: 'pe_ppl_l4',
            programDayId: 'day_ppl_leg1',
            exerciseId: 'ex_mach_standing_calf_raise',
            order: 4,
            sets: 4,
            repsMin: 12,
            repsMax: 15,
            targetWeight: 60,
            rpe: 8.5,
            restSeconds: 60,
            isOptional: false,
          },
        ],
      },
    ],
  },

  // 3. Reformer Pilates Foundations (3 Days/Week)
  {
    id: 'prog_lib_reformer_foundations',
    name: 'Reformer Pilates Foundations',
    goal: 'REHAB',
    weeks: 4,
    daysPerWeek: 3,
    notes: 'Designed by Sneha Rao for the Allegro 2 Reformer studio. Emphasizes lumbo-pelvic stabilization, spine articulation, and eccentric hamstring length.',
    ownerType: 'GYM',
    ownerId: 'gym_powai',
    visibility: 'GYM_LIBRARY',
    clonedFromId: null,
    days: [
      {
        id: 'day_ref_f1',
        programId: 'prog_lib_reformer_foundations',
        weekIndex: 0,
        dayIndex: 0,
        label: 'Session 1: Alignment & Core Integration',
        exercises: [
          {
            id: 'pe_ref1_1',
            programDayId: 'day_ref_f1',
            exerciseId: 'ex_ref_footwork_parallel',
            order: 1,
            sets: 3,
            repsMin: 12,
            repsMax: 15,
            rpe: 6.5,
            restSeconds: 45,
            coachNote: '2 Red, 1 Blue springs. Smooth piston-like cadence.',
            isOptional: false,
          },
          {
            id: 'pe_ref1_2',
            programDayId: 'day_ref_f1',
            exerciseId: 'ex_ref_hundred',
            order: 2,
            sets: 1,
            repsMin: 100,
            repsMax: 100,
            rpe: 8.5,
            restSeconds: 60,
            coachNote: '1 Red, 1 Blue springs. Vigorous arm pumping, hold 45-degree legs.',
            isOptional: false,
          },
          {
            id: 'pe_ref1_3',
            programDayId: 'day_ref_f1',
            exerciseId: 'ex_ref_elephant',
            order: 3,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            rpe: 7.0,
            restSeconds: 45,
            coachNote: '2 Red springs. Lift pelvic floor as carriage returns.',
            isOptional: false,
          },
          {
            id: 'pe_ref1_4',
            programDayId: 'day_ref_f1',
            exerciseId: 'ex_ref_mermaid',
            order: 4,
            sets: 2,
            repsMin: 6,
            repsMax: 8,
            rpe: 6.0,
            restSeconds: 30,
            coachNote: '1 Blue spring. Fluid lateral reach overhead.',
            isOptional: false,
          },
        ],
      },
      {
        id: 'day_ref_f2',
        programId: 'prog_lib_reformer_foundations',
        weekIndex: 0,
        dayIndex: 1,
        label: 'Session 2: Posterior Chain & Upper Back Mechanics',
        exercises: [
          {
            id: 'pe_ref2_1',
            programDayId: 'day_ref_f2',
            exerciseId: 'ex_ref_footwork_v_heels',
            order: 1,
            sets: 3,
            repsMin: 12,
            repsMax: 15,
            rpe: 7.0,
            restSeconds: 45,
            coachNote: 'High half-toe, maintain ankle flexion stability.',
            isOptional: false,
          },
          {
            id: 'pe_ref2_2',
            programDayId: 'day_ref_f2',
            exerciseId: 'ex_ref_pulling_straps',
            order: 2,
            sets: 3,
            repsMin: 8,
            repsMax: 10,
            rpe: 7.5,
            restSeconds: 45,
            coachNote: 'Long box, 1 Red spring. Draw scapulae together.',
            isOptional: false,
          },
          {
            id: 'pe_ref2_3',
            programDayId: 'day_ref_f2',
            exerciseId: 'ex_ref_feet_in_straps_circles',
            order: 3,
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            rpe: 6.5,
            restSeconds: 45,
            coachNote: '2 Red springs. Expansive circular leg arcs without pelvic tilt.',
            isOptional: false,
          },
          {
            id: 'pe_ref2_4',
            programDayId: 'day_ref_f2',
            exerciseId: 'ex_ref_eve_lunge',
            order: 4,
            sets: 2,
            repsMin: 6,
            repsMax: 8,
            rpe: 6.5,
            restSeconds: 45,
            coachNote: '1 Red, 1 Blue. Deep psoas stretch.',
            isOptional: true,
          },
        ],
      },
    ],
  },

  // 4. Fat Loss & Conditioning Circuit (4 Days/Week)
  {
    id: 'prog_lib_fat_loss_circuit',
    name: 'High-Density Fat Loss & Conditioning',
    goal: 'FAT_LOSS',
    weeks: 4,
    daysPerWeek: 4,
    notes: 'Designed to elevate EPOC and preserve lean tissue through compound functional resistance paired with high-cadence cardio intervals.',
    ownerType: 'GYM',
    ownerId: 'gym_powai',
    visibility: 'GYM_LIBRARY',
    clonedFromId: null,
    days: [
      {
        id: 'day_fl_1',
        programId: 'prog_lib_fat_loss_circuit',
        weekIndex: 0,
        dayIndex: 0,
        label: 'Circuit 1: Lower Body & Sled Velocity',
        exercises: [
          {
            id: 'pe_fl1_1',
            programDayId: 'day_fl_1',
            exerciseId: 'ex_kb_goblet_squat',
            order: 1,
            sets: 4,
            repsMin: 12,
            repsMax: 15,
            targetWeight: 20,
            rpe: 8.0,
            restSeconds: 45,
            isOptional: false,
          },
          {
            id: 'pe_fl1_2',
            programDayId: 'day_fl_1',
            exerciseId: 'ex_kb_kettlebell_swing',
            order: 2,
            sets: 4,
            repsMin: 15,
            repsMax: 20,
            targetWeight: 16,
            rpe: 8.5,
            restSeconds: 45,
            isOptional: false,
          },
          {
            id: 'pe_fl1_3',
            programDayId: 'day_fl_1',
            exerciseId: 'ex_cardio_sled_push',
            order: 3,
            sets: 4,
            repsMin: 1,
            repsMax: 1,
            targetWeight: 60,
            rpe: 9.0,
            restSeconds: 60,
            coachNote: '20-meter sprint on turf track.',
            isOptional: false,
          },
          {
            id: 'pe_fl1_4',
            programDayId: 'day_fl_1',
            exerciseId: 'ex_cardio_assault_bike',
            order: 4,
            sets: 4,
            durationSeconds: 45,
            rpe: 9.0,
            restSeconds: 60,
            coachNote: '45 seconds max effort sprint.',
            isOptional: false,
          },
        ],
      },
    ],
  },

  // 5. Hotel & Travel Dumbbell / Bodyweight (3 Days/Week)
  {
    id: 'prog_lib_travel_dumbbells',
    name: 'Hotel & Travel Dumbbell Protocol',
    goal: 'GENERAL',
    weeks: 4,
    daysPerWeek: 3,
    notes: 'Minimalist protocol requiring only a pair of light-to-moderate dumbbells and bodyweight. Keeps members active while traveling to Goa or abroad.',
    ownerType: 'GYM',
    ownerId: 'gym_powai',
    visibility: 'GYM_LIBRARY',
    clonedFromId: null,
    days: [
      {
        id: 'day_tr_1',
        programId: 'prog_lib_travel_dumbbells',
        weekIndex: 0,
        dayIndex: 0,
        label: 'Travel Full Body A',
        exercises: [
          {
            id: 'pe_tr1_1',
            programDayId: 'day_tr_1',
            exerciseId: 'ex_bw_pushups',
            order: 1,
            sets: 4,
            repsMin: 15,
            repsMax: 20,
            rpe: 8.0,
            restSeconds: 60,
            isOptional: false,
          },
          {
            id: 'pe_tr1_2',
            programDayId: 'day_tr_1',
            exerciseId: 'ex_db_one_arm_row',
            order: 2,
            sets: 4,
            repsMin: 12,
            repsMax: 15,
            targetWeight: 14,
            rpe: 8.0,
            restSeconds: 60,
            isOptional: false,
          },
          {
            id: 'pe_tr1_3',
            programDayId: 'day_tr_1',
            exerciseId: 'ex_db_walking_lunges',
            order: 3,
            sets: 4,
            repsMin: 12,
            repsMax: 16,
            targetWeight: 10,
            rpe: 8.0,
            restSeconds: 60,
            isOptional: false,
          },
          {
            id: 'pe_tr1_4',
            programDayId: 'day_tr_1',
            exerciseId: 'ex_core_plank',
            order: 4,
            sets: 3,
            durationSeconds: 60,
            rpe: 8.5,
            restSeconds: 45,
            isOptional: false,
          },
        ],
      },
    ],
  },
]
